version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: omneaxaflow-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: omneaxaflow-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - media_data:/app/media
    restart: unless-stopped

  worker:
    build: ./backend
    container_name: omneaxaflow-worker
    command: celery -A app.workers.celery_app worker --loglevel=info --pool=solo
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - media_data:/app/media
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: omneaxaflow-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: omneaxaflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: omneaxaflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  media_data:
